config/routes.rb
Rails.application.routes.draw do
  root to: 'questionnaires#index'
  get 'questionnaires/finish' => 'questionnaires#finish', as: 'finish_questionnaire'
  get 'questionnaires/:id/result' => 'questionnaires#result', as: 'result_questionnaire'
  get 'questionnaires/:id/answer/:no' => 'questionnaires#show_question', as: 'get_ans_question_questionnaire'
  post 'questionnaires/:id/answer/:no' => 'questionnaires#answer', as: 'post_answer_questionnaire'
  resources :questionnaires do
    resources :questions do
      resources :answers, only: [:create, :update]
    end
  end
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question
  belongs_to :respondent
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ApplicationRecord
  before_create :initialize_no
  after_destroy :destroy_organize_no

  belongs_to :questionnaire
  has_many :answers

  validates :title, presence: true
  validates :question_type, presence: true, inclusion: { in: Settings.question[:types_map].keys.map{|i| i.to_s} }
  validates :json_text, presence: true
  validate :json_array_lint

  def prev
    Question.find_by(questionnaire_id: questionnaire_id, no: no.to_i - 1)
  end

  def next
    Question.find_by(questionnaire_id: questionnaire_id, no: no.to_i + 1)
  end

  def final?
    self.next.blank?
  end

  def first?
    prev.blank?
  end

  private

  def initialize_no
    max_no_question = self.questionnaire.questions.order(no: 'DESC').limit(1).first
    self_no = max_no_question.present? ? max_no_question.no + 1 : 1
    self.no = self_no
  end

  def destroy_organize_no
    greater_no_questions = self.questionnaire.questions.where(Question.arel_table[:no].gt(self.no))
    greater_no_questions.each do |question|
      question.no = question.no - 1
      question.save
    end
  end

  def json_array_lint
    begin
      json = JSON.parse(json_text)
      unless json.instance_of?(Array)
        errors.add(:json_text, '形式が正しくないか不正な文字が含まれています')
      end
    rescue JSON::ParserError => e
      errors.add(:json_text, '形式が正しくないか不正な文字が含まれています')
    end
  end
end

app/models/questionnaire.rb
class Questionnaire < ApplicationRecord
  has_many :questions, dependent: :destroy
  has_many :respondents, dependent: :destroy

  VALID_DATE_FORMAT = /\d{4}\-(0?[1-9]|1[012])\-(0?[1-9]|[12][0-9]|3[01])*/
  validates :title, presence: true
  validates :start_date, presence: true, format: VALID_DATE_FORMAT
  validates :end_date, presence: true, format: VALID_DATE_FORMAT
  validate :end_date_after_start_date

  private

  def end_date_after_start_date
    if start_date.present? && end_date.present? && end_date < start_date
      errors.add(:end_date, '開始日以降を入力してください')
    end
  end
end

app/models/respondent.rb
class Respondent < ApplicationRecord
  belongs_to :questionnaire
  has_many :answers, dependent: :destroy
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :set_questionnaire
  before_action :set_question
  before_action :set_answer, only: :update

  def create
    @answer = Answer.new(answer_params)

    if @answer.save!
      redirect_to root_path, notice: '回答を追加しました'
    else
      render :new
    end
  end

  def update
    if @answer.update(answer_params)
      redirect_to root_path, notice: '回答を更新しました'
    else
      render :edit
    end
  end

  private

  def set_answer
    @answer = Answer.find(params[:id])
  end

  def set_question
    @question = Question.find(params[:question_id])
  end

  def set_questionnaire
    @questionnaire = Questionnaire.find(params[:questionnaire_id])
  end

  def answer_params
    params.require(:answer).permit(:question_id, :respondent_id, :json_text)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/questionnaires_controller.rb
class QuestionnairesController < ApplicationController
  before_action :set_questionnaire, only: %i[show edit update destroy show_question answer]
  before_action :set_question_by_no, only: %i[show_question answer]

  def index
    @questionnaires = Questionnaire.all.page(params[:page])
  end

  def show; end

  def new
    @questionnaire = Questionnaire.new
  end

  def edit; end

  def create
    @questionnaire = Questionnaire.new(questionnaire_params)

    if @questionnaire.save
      redirect_to questionnaires_url, notice: 'アンケートを追加しました'
    else
      render :new
    end
  end

  def update
    if @questionnaire.update(questionnaire_params)
      redirect_to questionnaires_url, notice: 'アンケートを更新しました'
    else
      render :edit
    end
  end

  def destroy
    @questionnaire.destroy
    redirect_to questionnaires_url, notice: 'アンケートを削除しました'
  end

  def finish; end

  def result
    set_questionnaire
  end

  def show_question
    @answer = @question.answers.build
    render 'question'
  end

  def answer

  end

  private

  def set_questionnaire
    @questionnaire = Questionnaire.find(params[:id])
  end

  def set_question_by_no
    @question = Questionnaire.find(params[:id]).questions.find_by(no: params[:no])
  end

  def questionnaire_params
    params.require(:questionnaire).permit(:title, :start_date, :end_date, :comment, :active)
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_questionnaire
  before_action :set_question, only: %i[show edit update destroy]

  def index
    @questions = @questionnaire.questions
  end

  def show; end

  def new
    @question = @questionnaire.questions.build
  end

  def edit; end

  def create
    @question = @questionnaire.questions.build(question_params)

    if @question.save
      redirect_to questionnaire_url(@questionnaire), notice: '質問を追加しました'
    else
      render :new
    end
  end

  def update
    if @question.update(question_params)
      redirect_to questionnaire_url(@questionnaire), notice: '質問を更新しました'
    else
      render :edit
    end
  end

  def destroy
    @question.destroy
    redirect_to questionnaire_url(@questionnaire), notice: '質問を削除しました'
  end

  private

  def set_question
    @question = Question.find(params[:id])
  end

  def set_questionnaire
    @questionnaire = Questionnaire.find(params[:questionnaire_id])
  end

  def question_params
    params.require(:question).permit(:title, :question_type, :json_text)
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questionnaires_helper.rb
module QuestionnairesHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/answers/_form.html.erb
<%= form_with(model: answer, local: true) do |form| %>
  <% if answer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(answer.errors.count, "error") %> prohibited this answer from being saved:</h2>

      <ul>
      <% answer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit '登録する', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/answers/edit.html.erb
<h1>Editing Answer</h1>

<%= render 'form', answer: @answer %>

<%= link_to 'Show', @answer %> |
<%= link_to 'Back', answers_path %>

app/views/answers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Answers</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @answers.each do |answer| %>
      <tr>
        <td><%= link_to 'Show', answer %></td>
        <td><%= link_to 'Edit', edit_answer_path(answer) %></td>
        <td><%= link_to 'Destroy', answer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Answer', new_answer_path %>

app/views/answers/new.html.erb
<h1>New Answer</h1>

<%= render 'form', answer: @answer %>

<%= link_to 'Back', answers_path %>

app/views/answers/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_answer_path(@answer) %> |
<%= link_to 'Back', answers_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>アンケート</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <button type="button" class="navbar-toggler">
        <span class="navbar-toggler-icon"></span>
      </button>
      <%= link_to 'アンケート', root_path, class: 'navbar-brand' %>
    </nav>
    <br>
    <% if notice.present? %>
      <div class="col-md-8 mx-auto">
        <div class="alert alert-success">
          <i class="fa fa-info-circle" aria-hidden="true"></i>&nbsp;<%= notice %>
        </div>
      </div>
    <% end %>
    <div class="container">
      <div class="col-md-12 mx-auto">
        <%= yield %>
      </div>
    </div>
    <footer class="footer">
      <div class="container">
        <p class="text-muted">Questionnaire system.</p>
      </div>
    </footer>
  </body>
</html>

app/views/questionnaires/_form.html.erb
<%= form_with(model: questionnaire, local: true) do |f| %>
  <div class="form-group row">
    <label class="col-sm-2 col-form-label">タイトル</label>
    <div class="col-sm-10">
      <% if questionnaire.errors.messages[:title].blank? %>
        <%= f.text_field :title, class: 'form-control' %>
      <% else %>
        <%= f.text_field :title, class: 'form-control is-invalid' %>
        <span class="text-danger">
          <%= questionnaire.errors.messages[:title].first %>
        </span>
      <% end %>
    </div>
  </div>
  <div class="form-group row">
    <label class="col-sm-2 col-form-label">開始日</label>
    <div class="col-sm-10">
      <div class="input-group mr-sm-2">
        <div class="input-group-addon"><i class="fa fa-calendar" aria-hidden="true"></i></div>
        <% if questionnaire.errors.messages[:start_date].blank? %>
          <%= f.text_field :start_date, class: 'form-control datepicker' %>
        <% else %>
          <%= f.text_field :start_date, class: 'form-control datepicker is-invalid' %>
        <% end %>
      </div>
      <% if questionnaire.errors.messages[:start_date].present? %>
        <span class="text-danger">
          <%= questionnaire.errors.messages[:start_date].first %>
        </span>
      <% end %>
    </div>
  </div>
  <div class="form-group row">
    <label class="col-sm-2 col-form-label">終了日</label>
    <div class="col-sm-10">
      <div class="input-group mr-sm-2">
        <div class="input-group-addon"><i class="fa fa-calendar" aria-hidden="true"></i></div>
        <% if questionnaire.errors.messages[:end_date].blank? %>
          <%= f.text_field :end_date, class: 'form-control datepicker' %>
        <% else %>
          <%= f.text_field :end_date, class: 'form-control datepicker is-invalid' %>
        <% end %>
      </div>
      <% if questionnaire.errors.messages[:end_date].present? %>
        <span class="text-danger">
          <%= questionnaire.errors.messages[:end_date].first %>
        </span>
      <% end %>
    </div>
  </div>
  <fieldset class="form-group">
    <div class="row">
      <legend class="col-form-legend col-sm-2">有効/無効</legend>
      <div class="col-sm-10">
        <label class="custom-control custom-radio">
          <%= f.radio_button :active, true, class: 'custom-control-input your-checkbox' %>
          <span class="custom-control-indicator"></span>
          <span class="custom-control-description">有効</span>
        </label>
        <label class="custom-control custom-radio">
          <%= f.radio_button :active, false, class: 'custom-control-input your-checkbox' %>
          <span class="custom-control-indicator"></span>
          <span class="custom-control-description">無効</span>
        </label>
      </div>
    </div>
  </fieldset>
  <div class="form-group row">
    <label class="col-sm-2 col-form-label">コメント</label>
    <div class="col-sm-10">
      <%= f.text_area :comment, class: 'form-control' %>
    </div>
  </div>
  <div class="actions form-group row">
    <div class="offset-sm-2 col-sm-10">
      <%= f.submit '登録する', class: 'btn btn-primary' %>
    </div>
  </div>
<% end %>
<%= link_to 'アンケート一覧へ戻る', questionnaires_path, class: 'btn btn-success btn-sm' %>

app/views/questionnaires/edit.html.erb
<h1>アンケート編集</h1>
<hr>

<%= render 'form', questionnaire: @questionnaire %>

app/views/questionnaires/finish.html.erb
<p id="notice"><%= notice %></p>

<h1>Finish</h1>

<%= link_to 'アンケート', root_path %>

app/views/questionnaires/index.html.erb
<h1>アンケート一覧</h1>
<hr>
<% if @questionnaires.present? %>
<table class="table table-striped">
  <thead>
    <tr>
      <th></th>
      <th>タイトル</th>
      <th>開始日</th>
      <th>終了日</th>
      <th>有効/無効</th>
      <th>コメント</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @questionnaires.each do |questionnaire| %>
      <tr>
        <td>
          <% if questionnaire.questions.count != 0 && questionnaire.active? %>
            <%= link_to get_ans_question_questionnaire_path(questionnaire, 1), class: 'btn btn-sm btn-success' do %>
              <i class="fa fa-mouse-pointer" aria-hidden="true"></i> 回答する
            <% end %>
          <% else %>
            <button type="button" class="btn btn-sm btn-success" disabled>
              <i class="fa fa-mouse-pointer" aria-hidden="true"></i> 回答する
            </button>
          <% end %>
        </td>
        <td><%= questionnaire.title %></td>
        <td><%= questionnaire.start_date %></td>
        <td><%= questionnaire.end_date %></td>
        <td>
          <% if questionnaire.active? %>
            有効
          <% else %>
            無効
          <% end %>
        </td>
        <td><%= questionnaire.comment %></td>
        <td>
          <%= link_to questionnaire_path(questionnaire), class: 'btn btn-sm btn-info' do %>
            <i class="fa fa-external-link" aria-hidden="true"></i> 詳細
          <% end %>
          <%= link_to edit_questionnaire_path(questionnaire), class: 'btn btn-sm btn-primary' do %>
            <i class="fa fa-pencil-square-o" aria-hidden="true"></i> 編集
          <% end %>
          <%= link_to questionnaire, method: :delete, data: { confirm: 'アンケートを削除します、よろしいですか？' }, class: 'btn btn-sm btn-danger' do %>
            <i class="fa fa-times" aria-hidden="true"></i> 削除
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<% else %>
  <p>アンケートはありません</p>
<% end %>

<%= paginate @questionnaires %>

<hr>
<%= link_to new_questionnaire_path, class: 'btn btn-primary' do %>
  <i class="fa fa-plus" aria-hidden="true"></i> 新規作成
<% end %>

app/views/questionnaires/new.html.erb
<h1>新規アンケート</h1>
<hr>

<%= render 'form', questionnaire: @questionnaire %>

app/views/questionnaires/question.html.erb
<h1><%= @question.title %></h1>
<hr>
<%= form_with(model: @answer, locale: true, url: questionnaire_question_answers_path(@questionnaire, @question)) do |f| %>
  <div class="form-group row">
    <label class="col-sm-2 col-form-label">回答一覧</label>
    <div class="col-sm-10">
      <% question_selection = JSON.parse(@question.json_text) %>
      <% question_selection.each.with_index(1) do |selection, index| %>
        <label class="custom-control custom-radio">
          <%= f.radio_button :active, index, class: 'custom-control-input' %>
          <span class="custom-control-indicator"></span>
          <span class="custom-control-description"><%= selection %></span>
        </label>
        <br>
      <% end %>
    </div>
  </div>
<% end %>

<% if @question.first? %>
  <button type="button" class="btn btn-success btn-sm" disabled>
    <i class="fa fa-arrow-left" aria-hidden="true"></i> 前へ
  </button>
<% else %>
  <%= link_to get_ans_question_questionnaire_path(@questionnaire, @question.prev.no), class: 'btn btn-success btn-sm' do %>
    <i class="fa fa-arrow-left" aria-hidden="true"></i> 前へ
  <% end %>
<% end %>

<% if @question.final? %>
  <button type="button" class="btn btn-primary btn-sm">
    <i class="fa fa-check-circle-o" aria-hidden="true"></i> 回答して終了する
  </button>
<% else %>
  <%= link_to get_ans_question_questionnaire_path(@questionnaire, @question.next.no), class: 'btn btn-success btn-sm' do %>
    次へ <i class="fa fa-arrow-right" aria-hidden="true"></i>
  <% end %>
<% end %>

<script type="text/javascript">

</script>

app/views/questionnaires/result.html.erb
<p id="notice"><%= notice %></p>

<h1>Finish</h1>

<br>

<%= link_to 'アンケート', root_path %>

app/views/questionnaires/show.html.erb
<h1>アンケート詳細</h1>
<hr>

<table class="table table-striped">
  <thead>
    <tr>
      <th>タイトル</th>
      <th>開始日</th>
      <th>終了日</th>
      <th>有効/無効</th>
      <th>コメント</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><%= @questionnaire.title %></td>
      <td><%= @questionnaire.start_date %></td>
      <td><%= @questionnaire.end_date %></td>
      <td>
        <% if @questionnaire.active? %>
          有効
        <% else %>
          無効
        <% end %>
      </td>
      <td><%= @questionnaire.comment %></td>
    </tr>
  </tbody>
</table>

<%= link_to edit_questionnaire_path(@questionnaire), class: 'btn btn-sm btn-primary' do %>
  <i class="fa fa-pencil-square-o" aria-hidden="true"></i> 編集
<% end %>
&nbsp;
<%= link_to questionnaire_path(@questionnaire), method: :delete, data: { confirm: '質問を削除します、よろしいですか？' }, class: 'btn btn-sm btn-danger' do %>
  <i class="fa fa-times" aria-hidden="true"></i> 削除
<% end %>
&nbsp;
<%= link_to 'アンケート一覧へ戻る', questionnaires_path, class: 'btn btn-sm btn-success' %>

<hr>
<h2>質問一覧</h2>
<% if(@questionnaire.questions.present?) %>
<table class="table table-striped">
  <thead>
    <tr>
      <th>No.</th>
      <th>タイトル</th>
      <th>質問タイプ</th>
      <th>質問個数</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
  <% @questionnaire.questions.each do |question| %>
    <tr>
      <td><%= question.no %></td>
      <td><%= question.title %></td>
      <td><%= Settings.question[:types_map][question.question_type] %></td>
      <td><%= question.json_text.present? ? JSON.parse(question.json_text).length : 0 %></td>
      <td>
        <%= link_to questionnaire_question_path(@questionnaire, question), class: 'btn btn-sm btn-info' do %>
          <i class="fa fa-external-link" aria-hidden="true"></i> 詳細
        <% end %>
        <%= link_to edit_questionnaire_question_path(@questionnaire, question), class: 'btn btn-sm btn-primary' do %>
          <i class="fa fa-pencil-square-o" aria-hidden="true"></i> 編集
        <% end %>
        <%= link_to questionnaire_question_path(@questionnaire, question), method: :delete, data: { confirm: 'アンケートを削除します、よろしいですか？' }, class: 'btn btn-sm btn-danger' do %>
          <i class="fa fa-times" aria-hidden="true"></i> 削除
        <% end %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>
<% else %>
  <p>質問はありません</p>
<% end %>
<hr>
<%= link_to new_questionnaire_question_path(@questionnaire), class: 'btn btn-primary' do %>
  <i class="fa fa-plus" aria-hidden="true"></i> 質問追加
<% end %>

app/views/questions/_form.html.erb
<%= form_with(model: question, local: true, url: url, id: 'form') do |f| %>
  <div class="form-group row">
    <label class="col-sm-2 col-form-label">タイトル</label>
    <div class="col-sm-10">
      <% if question.errors[:title].blank? %>
        <%= f.text_field :title, class: 'form-control' %>
      <% else %>
        <%= f.text_field :title, class: 'form-control is-invalid' %>
        <span class="text-danger">
          <%= question.errors[:title].first %>
        </span>
      <% end %>
    </div>
  </div>
  <div class="form-group row">
    <label class="col-sm-2 col-form-label">質問タイプ</label>
    <div class="col-sm-10">
      <% if question.errors[:question_type].blank? %>
        <%= f.select :question_type, Settings.question[:types_map].to_a.map{|i| i.reverse}, {}, class: 'form-control' %>
      <% else %>
        <%= f.select :question_type, Settings.question[:types_map].to_a.map{|i| i.reverse}, {}, class: 'form-control is-invalid' %>
        <span class="text-danger">
          <%= question.errors[:question_type].first %>
        </span>
      <% end %>
    </div>
  </div>
  <hr>
  <div id="selection-form">
    <% if question[:json_text].present? %>
      <% question_selections = JSON.parse(question[:json_text]) %>
      <% first_question_selection = question_selections.shift %>
      <div class="actions form-group row">
        <label class="col-sm-2 col-form-label">質問</label>
        <div class="col-sm-10">
          <% if question.errors[:json_text].blank? %>
            <input title="selection" class="form-control selection" value="<%= first_question_selection.to_s %>" />
          <% else %>
            <input title="selection" class="form-control selection is-invalid" value="<%= first_question_selection.to_s %>" />
            <span class="text-danger">
              <%= question.errors[:json_text].first %>
            </span>
          <% end %>
        </div>
      </div>
      <% question_selections.each do |selection| %>
        <div class="actions form-group row">
          <div class="offset-sm-2 col-sm-9">
            <input title="selection" class="form-control selection" value="<%= selection.to_s %>" />
          </div>
          <div class="col-sm-1">
            <button type="button" class="btn btn-danger remove-selection">
              <i class="fa fa-times" aria-hidden="true"></i>
            </button>
          </div>
        </div>
      <% end %>
    <% else %>
      <div class="actions form-group row">
        <label class="col-sm-2 col-form-label">質問</label>
        <div class="col-sm-10">
          <input title="selection" class="form-control selection" value="" />
        </div>
      </div>
    <% end %>
  </div>
  <div class="form-group row">
    <div class="offset-sm-2 col-sm-10">
      <button class="btn btn-info btn-sm" id="add-selection" type="button">
        <i class="fa fa-plus" aria-hidden="true"></i> 選択肢追加
      </button>
    </div>
  </div>
  <div class="actions form-group row">
    <div class="offset-sm-2 col-sm-10">
      <%= f.submit '登録する', class: 'btn btn-primary', id: 'submit-btn' %>
    </div>
  </div>
<% end %>
<%= link_to 'アンケート詳細へ戻る', questionnaire_path(@questionnaire), class: 'btn btn-success btn-sm' %>
<script type="text/javascript">
  var count = 1;
  const animationMills = 500;
  var selectionInput = (function() {
      /*
      <div class="actions form-group row">
        <div class="offset-sm-2 col-sm-9">
          <input class="form-control selection" />
        </div>
        <div class="col-sm-1">
          <button type="button" class="btn btn-danger remove-selection">
            <i class="fa fa-times" aria-hidden="true"></i>
          </button>
        </div>
      </div>
       */
  }).toString().match(/(?:\/\*(?:[\s\S]*?)\*\/)/).pop().replace(/^\/\*/, "").replace(/\*\/$/, "");

  var validationMessage = '<span class="text-danger">値が空です</span>';

  // on click add selection input tag.
  $('#add-selection').on('click', function() {
    $(selectionInput).appendTo('#selection-form').hide().fadeIn(animationMills);
  });

  // on click remove selection input tag.
  $(document).on('click', '.remove-selection', function() {
    var target = $(this).parent().parent();
    target.fadeOut(animationMills, function() {
      $(this).remove();
    });
  });

  // before submit create hidden tag.
  $(document).on('submit', '#form', function() {
    var form = $(this);
    var selections = [];
    var hasError = false;
    $('.selection').each(function() {
      var elem = $(this);
      var selectionValue = elem.val();
      if(!selectionValue) {
        if(!elem.hasClass('is-invalid')) {
          elem.addClass('is-invalid');
          elem.parent().append(validationMessage);
        }
        hasError = true;
      } else {
        elem.removeClass('is-invalid');
        elem.parent().children('span').remove();
      }
      selections.push(selectionValue);
    });
    if(hasError) {
      // remove disabled after submit.
      setTimeout(function() {
        if(hasError) $('#submit-btn').removeAttr('disabled');
      }, 100);
      return false;
    } else {
      var json = escapeHTML(JSON.stringify(selections));
      form.append('<input type="hidden" name="question[json_text]" value="' + json + '" />');
      form.submit();
    }
  });
</script>

app/views/questions/edit.html.erb
<h1>質問詳細</h1>
<hr>

<%= render 'form', question: @question, url: questionnaire_question_path(@questionnaire, @question) %>

app/views/questions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Questions</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @questions.each do |question| %>
      <tr>
        <td><%= link_to 'Show', question %></td>
        <td><%= link_to 'Edit', edit_question_path(question) %></td>
        <td><%= link_to 'Destroy', question, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Question', new_question_path %>

app/views/questions/new.html.erb
<h1>新規質問</h1>
<hr>

<%= render 'form', question: @question, url: questionnaire_questions_path(@questionnaire) %>

app/views/questions/show.html.erb
<h1>質問詳細</h1>
<hr>

<table class="table table-striped">
  <tr>
    <th>No.</th>
    <td><%= @question.no %></td>
  </tr>
  <tr>
    <th>タイトル</th>
    <td><%= @question.title %></td>
  </tr>
  <tr>
    <th>質問タイプ</th>
    <td><%= Settings.question[:types_map][@question.question_type] %></td>
  </tr>
</table>
<hr>
<h3>選択</h3>
<table class="table table-striped">
  <% JSON.parse(@question.text).each do |selection| %>
    <tr>
      <td><%= selection %></td>
    </tr>
  <% end %>
</table>

<hr>
<%= link_to 'アンケート詳細へ戻る', questionnaire_path(@questionnaire), class: 'btn btn-sm btn-success' %>